export const styleSbmtBtns = {
  textDecoration: 'none',
  fontSize: '14px',
  fontFamily: 'Arial',
  width: '100px',
  height: '38px',
  borderWidth: '1px',
  color: '#fff',
  borderColor: '#d02718',
  fontWeight: 'bold',
  borderTopLeftRadius: '18px',
  borderTopRightRadius: '18px',
  borderBottomLeftRadius: '18px',
  borderBottomRightRadius: '1px',
  boxShadow: '3px 4px 0px 0px #8a2a21',
  textShadow: '0px 1px 0px #810e05',
  background: 'linear-gradient(#c62d1f, #f24437)',
  marginTop: '10px',
};
